
% compute the model from "Spatio-Temporal Patterns Generated by 
% Salmonella typhimurium "

%% load parameters.
alpha = 3.0;
beta  = 2.0;
gamma = 0.2;
rho   = 0.03;
Dn    = 0.1;
Dc    = 0.3;
% Dot cont parameter.
s = 1;

length = 3;
tend = 5;

dt = 0.001;
dx = 0.1;
J = 20;

%there are only cells at the center.
[x,y] = meshgrid(linspace(0,1,J));
N = 15*(x - x.^2).*(y-y.^2).*exp(-50 .*((x - 0.5).^2 + (y - 0.5).^2 ));
Nnew = N;
%transmitters are zero initially.
C = 0.*x+0.*y;
Cnew = C;

%% start computation!
for t = 1:floor(tend/dt)
    
    for i = 2:(J-1)
        for j = 2:(J-1)
            
        Nnew(i,j) = N(i,j) + dt*( Dn/(dx^2)*(N(i+1,j) + N(i-1,j) + ...
                    N(i,j+1) + N(i,j-1) - 4*N(i,j))  ...
                    - (N(i,j) * alpha) / (1 + beta*C(i,j)) *    ...
                    (N(i-1,j) + N(i+1,j) + N(i,j+1) + N(i,j-1)) *  ... 
                    (C(i-1,j) + C(i+1,j) + C(i,j+1) + C(i,j-1))/(dx) ...
                    + rho*N(i,j)*( 1  - N(i,j)/s));
                
        Cnew(i,j) = C(i,j) + dt*( Dc * (C(i+1,j) + C(i-1,j) + C(i,j+1) + ...
                    C(i,j-1) - 4*C(i,j))/(dx^2) ...
                    + s*N(i,j)/(1 + gamma*N(i,j))  ...
                    - C(i,j)*N(i,j)/(1 + gamma*C(i,j)) );
    
        end
    end
    N = Nnew;
    C = Cnew;
end
figure(1)
surf(N);
figure(2)
surf(C);

