
% compute the model from "Spatio-Temporal Patterns Generated by 
% Salmonella typhimurium "

%% load parameters.
alpha = 3.0;
beta  = 2.0;
gamma = 0.2;
%gamma = 0;
rho   = 0.03;
Dn    = 0.1;
Dc    = 0.3;
% Bifurcataion parameter.
s = 1.5;
%pattern propagation.
r = 0.8;
%r = 1;

length = 3;
tend = 6;

dt = 0.0005
J = 60;
idx = 2:(J-1);

dx = length/J
dy = dx;

mu = dt/(dx)^2

steps = floor(tend/dt)

%there are only cells at the center.
[x,y] = meshgrid(linspace(0,1,J));
%N = 15*(x - x.^2).*(y-y.^2).*exp(-50 .*((x - 0.5).^2 + (y - 0.5).^2 ));

N = 0.*x + 0.*y;
N((J/2-10):(J/2+10),(J/2-10):(J/2+10)) = 1;
Nnew = N;

%transmitters are zero initially.
C = 0.*x+0.*y;
Cnew = C;

%% start computation!
for t = 1:steps
    
 %approximate the chemotaxis half steps! North, East, South, West:
 a = N./(1 + beta.*C);
 aN = ( a(idx,idx+1) + a(idx,idx) )./2;
 aE = ( a(idx+1,idx) + a(idx,idx) )./2;
 aS = ( a(idx,idx-1) + a(idx,idx) )./2;
 aW = ( a(idx-1,idx) + a(idx,idx) )./2;
 
 %compute the logistic growth term.
 f = rho.*N(idx,idx).*( 1  - N(idx,idx)./s);
      
 Nnew(idx,idx) = N(idx,idx) + dt.*( f ...
                ... diffusion term.
                 +(Dn/(dx)^2) .*(N(idx+1,idx) + N(idx-1,idx) + ...
                 N(idx,idx+1) + N(idx,idx-1) - 4.*N(idx,idx))  ...
                 ... %chemotaxis term.
                 -(alpha/dx^2).*( aE.*(C(idx+1,idx) - C(idx,idx))    ...
                                - aW.*(C(idx,idx)   - C(idx-1,idx)) ...
                                + aN.*(C(idx,idx+1) - C(idx,idx)) ... 
                                - aS.*(C(idx,idx)   - C(idx,idx-1))));              
        
 %Only the growth model.
 %Nnew(i,j) = N(i,j) + dt*( rho*N(i,j)*( 1  - N(i,j)/s));
  
                     %diffusion term
 Cnew(idx,idx) = C(idx,idx) + dt*( Dc/(dx^2) .* (C(idx+1,idx) + ...
                 C(idx-1,idx) + C(idx,idx+1) + ...
                 C(idx,idx-1) - 4.*C(idx,idx))  ...
                 ... %production term
                 + s.*N(idx,idx)./(1 + gamma.*N(idx,idx))  ...
                 ... %consumption term
                 - (C(idx,idx).*(N(idx,idx).^r))./(1 + gamma.*C(idx,idx)));
    
   N = Nnew;
   C = Cnew;
end
figure(1)
surf(real(N));shading('flat');
figure(2)
surf(real(C));shading('flat');

